"""add practice attempt logical question identity

Revision ID: 0ae13d3f1466
Revises: 6526873c524c
Create Date: 2026-09-05 23:18:43.417979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ae13d3f1466'
down_revision: Union[str, Sequence[str], None] = '6526873c524c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practice_attempt_question_identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_group_id', sa.Integer(), nullable=True),
    sa.Column('logical_question_key', sa.String(length=200), nullable=False),
    sa.Column('group_key', sa.String(length=150), nullable=True),
    sa.Column('question_type', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['practice_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_group_id'], ['curriculum_question_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', name='uq_practice_attempt_question_identity')
    )
    op.create_index(op.f('ix_practice_attempt_question_identities_attempt_id'), 'practice_attempt_question_identities', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_practice_attempt_question_identities_logical_question_key'), 'practice_attempt_question_identities', ['logical_question_key'], unique=False)
    op.create_index(op.f('ix_practice_attempt_question_identities_question_group_id'), 'practice_attempt_question_identities', ['question_group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_practice_attempt_question_identities_question_group_id'), table_name='practice_attempt_question_identities')
    op.drop_index(op.f('ix_practice_attempt_question_identities_logical_question_key'), table_name='practice_attempt_question_identities')
    op.drop_index(op.f('ix_practice_attempt_question_identities_attempt_id'), table_name='practice_attempt_question_identities')
    op.drop_table('practice_attempt_question_identities')
    # ### end Alembic commands ###
