"""add students and practice attempts

Revision ID: 0dfe94a2c780
Revises: 30381adada44
Create Date: 2026-09-05 08:53:16.353023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dfe94a2c780'
down_revision: Union[str, Sequence[str], None] = '30381adada44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('practice_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('curriculum_id', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('lesson_number', sa.String(length=50), nullable=True),
    sa.Column('student_answer', sa.Text(), nullable=False),
    sa.Column('evaluation_status', sa.String(length=50), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('solution_source', sa.String(length=50), nullable=True),
    sa.Column('ai_provider', sa.String(length=50), nullable=True),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['curriculum_chunks.id'], ),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curricula.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_attempts_chunk_id'), 'practice_attempts', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_practice_attempts_curriculum_id'), 'practice_attempts', ['curriculum_id'], unique=False)
    op.create_index(op.f('ix_practice_attempts_student_id'), 'practice_attempts', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_practice_attempts_student_id'), table_name='practice_attempts')
    op.drop_index(op.f('ix_practice_attempts_curriculum_id'), table_name='practice_attempts')
    op.drop_index(op.f('ix_practice_attempts_chunk_id'), table_name='practice_attempts')
    op.drop_table('practice_attempts')
    op.drop_table('students')
    # ### end Alembic commands ###
