"""add curriculum concepts

Revision ID: 2d28d2e30428
Revises: b40b7f609f10
Create Date: 2026-09-05 10:16:04.742777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d28d2e30428'
down_revision: Union[str, Sequence[str], None] = 'b40b7f609f10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curriculum_concepts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curriculum_id', sa.Integer(), nullable=False),
    sa.Column('lesson_number', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curricula.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('curriculum_id', 'lesson_number', 'code', name='uq_curriculum_concept_scope')
    )
    op.create_index(op.f('ix_curriculum_concepts_curriculum_id'), 'curriculum_concepts', ['curriculum_id'], unique=False)
    op.create_index(op.f('ix_curriculum_concepts_lesson_number'), 'curriculum_concepts', ['lesson_number'], unique=False)
    op.create_table('curriculum_chunk_concepts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['curriculum_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['concept_id'], ['curriculum_concepts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_id', 'concept_id', name='uq_curriculum_chunk_concept')
    )
    op.create_index(op.f('ix_curriculum_chunk_concepts_chunk_id'), 'curriculum_chunk_concepts', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_curriculum_chunk_concepts_concept_id'), 'curriculum_chunk_concepts', ['concept_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_curriculum_chunk_concepts_concept_id'), table_name='curriculum_chunk_concepts')
    op.drop_index(op.f('ix_curriculum_chunk_concepts_chunk_id'), table_name='curriculum_chunk_concepts')
    op.drop_table('curriculum_chunk_concepts')
    op.drop_index(op.f('ix_curriculum_concepts_lesson_number'), table_name='curriculum_concepts')
    op.drop_index(op.f('ix_curriculum_concepts_curriculum_id'), table_name='curriculum_concepts')
    op.drop_table('curriculum_concepts')
    # ### end Alembic commands ###
