"""add curriculum question solutions

Revision ID: 30381adada44
Revises: 5c2cc936c38d
Create Date: 2026-09-04 15:24:10.309339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30381adada44'
down_revision: Union[str, Sequence[str], None] = '5c2cc936c38d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curriculum_question_solutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('final_answer', sa.Text(), nullable=False),
    sa.Column('solution_steps', sa.Text(), nullable=True),
    sa.Column('solution_source', sa.String(length=50), nullable=False),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['curriculum_chunks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curriculum_question_solutions_chunk_id'), 'curriculum_question_solutions', ['chunk_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_curriculum_question_solutions_chunk_id'), table_name='curriculum_question_solutions')
    op.drop_table('curriculum_question_solutions')
    # ### end Alembic commands ###
