"""add lesson metadata to curriculum pages

Revision ID: 5c2cc936c38d
Revises: 95e1196e0cdc
Create Date: 2026-09-04 12:28:21.952137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c2cc936c38d'
down_revision: Union[str, Sequence[str], None] = '95e1196e0cdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curriculum_pages', sa.Column('lesson_number', sa.String(length=50), nullable=True))
    op.add_column('curriculum_pages', sa.Column('lesson_title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('curriculum_pages', 'lesson_title')
    op.drop_column('curriculum_pages', 'lesson_number')
    # ### end Alembic commands ###
