"""add curriculum question groups

Revision ID: 6526873c524c
Revises: b5580545cd26
Create Date: 2026-09-05 13:01:54.081753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6526873c524c'
down_revision: Union[str, Sequence[str], None] = 'b5580545cd26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curriculum_question_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('lesson_number', sa.String(length=50), nullable=True),
    sa.Column('group_key', sa.String(length=150), nullable=False),
    sa.Column('question_number', sa.String(length=50), nullable=True),
    sa.Column('question_type', sa.String(length=50), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['curriculum_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'page_number', 'group_key', name='uq_curriculum_question_group')
    )
    op.create_index(op.f('ix_curriculum_question_groups_document_id'), 'curriculum_question_groups', ['document_id'], unique=False)
    op.create_index(op.f('ix_curriculum_question_groups_lesson_number'), 'curriculum_question_groups', ['lesson_number'], unique=False)
    op.create_index(op.f('ix_curriculum_question_groups_page_number'), 'curriculum_question_groups', ['page_number'], unique=False)
    op.create_table('curriculum_question_group_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_group_id', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['curriculum_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_group_id'], ['curriculum_question_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_group_id', 'chunk_id', name='uq_question_group_chunk')
    )
    op.create_index(op.f('ix_curriculum_question_group_chunks_chunk_id'), 'curriculum_question_group_chunks', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_curriculum_question_group_chunks_question_group_id'), 'curriculum_question_group_chunks', ['question_group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_curriculum_question_group_chunks_question_group_id'), table_name='curriculum_question_group_chunks')
    op.drop_index(op.f('ix_curriculum_question_group_chunks_chunk_id'), table_name='curriculum_question_group_chunks')
    op.drop_table('curriculum_question_group_chunks')
    op.drop_index(op.f('ix_curriculum_question_groups_page_number'), table_name='curriculum_question_groups')
    op.drop_index(op.f('ix_curriculum_question_groups_lesson_number'), table_name='curriculum_question_groups')
    op.drop_index(op.f('ix_curriculum_question_groups_document_id'), table_name='curriculum_question_groups')
    op.drop_table('curriculum_question_groups')
    # ### end Alembic commands ###
