"""add question group solutions

Revision ID: 66deed8153a3
Revises: 0ae13d3f1466
Create Date: 2026-09-06 00:01:02.056403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66deed8153a3'
down_revision: Union[str, Sequence[str], None] = '0ae13d3f1466'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curriculum_question_group_solutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_group_id', sa.Integer(), nullable=False),
    sa.Column('answer_payload', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('solution_source', sa.String(length=50), nullable=False),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_group_id'], ['curriculum_question_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curriculum_question_group_solutions_question_group_id'), 'curriculum_question_group_solutions', ['question_group_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_curriculum_question_group_solutions_question_group_id'), table_name='curriculum_question_group_solutions')
    op.drop_table('curriculum_question_group_solutions')
    # ### end Alembic commands ###
