"""add chunk embeddings

Revision ID: 95e1196e0cdc
Revises: c62e591b996a
Create Date: 2026-09-03 17:00:05.295088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import VECTOR


# revision identifiers, used by Alembic.
revision: str = '95e1196e0cdc'
down_revision: Union[str, Sequence[str], None] = 'c62e591b996a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curriculum_chunks', sa.Column('embedding', VECTOR(), nullable=True))
    op.add_column('curriculum_chunks', sa.Column('embedding_provider', sa.String(length=50), nullable=True))
    op.add_column('curriculum_chunks', sa.Column('embedding_model', sa.String(length=100), nullable=True))
    op.add_column('curriculum_chunks', sa.Column('embedding_dimensions', sa.Integer(), nullable=True))
    op.add_column('curriculum_chunks', sa.Column('embedded_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('curriculum_chunks', 'embedded_at')
    op.drop_column('curriculum_chunks', 'embedding_dimensions')
    op.drop_column('curriculum_chunks', 'embedding_model')
    op.drop_column('curriculum_chunks', 'embedding_provider')
    op.drop_column('curriculum_chunks', 'embedding')
    # ### end Alembic commands ###
