"""add practice attempt concept snapshots

Revision ID: b2a6aabcbe64
Revises: 2d28d2e30428
Create Date: 2026-09-05 10:25:54.239171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2a6aabcbe64'
down_revision: Union[str, Sequence[str], None] = '2d28d2e30428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practice_attempt_concepts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=True),
    sa.Column('concept_code', sa.String(length=100), nullable=False),
    sa.Column('concept_name', sa.String(length=150), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['practice_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['concept_id'], ['curriculum_concepts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'concept_code', name='uq_practice_attempt_concept')
    )
    op.create_index(op.f('ix_practice_attempt_concepts_attempt_id'), 'practice_attempt_concepts', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_practice_attempt_concepts_concept_id'), 'practice_attempt_concepts', ['concept_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_practice_attempt_concepts_concept_id'), table_name='practice_attempt_concepts')
    op.drop_index(op.f('ix_practice_attempt_concepts_attempt_id'), table_name='practice_attempt_concepts')
    op.drop_table('practice_attempt_concepts')
    # ### end Alembic commands ###
