"""preserve practice attempt history

Revision ID: b40b7f609f10
Revises: 0dfe94a2c780
Create Date: 2026-09-05 09:00:28.037896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b40b7f609f10'
down_revision: Union[str, Sequence[str], None] = '0dfe94a2c780'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practice_attempts', sa.Column('question_number', sa.String(length=50), nullable=True))
    op.add_column('practice_attempts', sa.Column('question_content', sa.Text(), nullable=False))
    op.add_column('practice_attempts', sa.Column('lesson_title', sa.String(length=255), nullable=True))
    op.add_column('practice_attempts', sa.Column('reference_answer', sa.Text(), nullable=True))
    op.alter_column('practice_attempts', 'chunk_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('practice_attempts_chunk_id_fkey'), 'practice_attempts', type_='foreignkey')
    op.create_foreign_key(None, 'practice_attempts', 'curriculum_chunks', ['chunk_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'practice_attempts', type_='foreignkey')
    op.create_foreign_key(op.f('practice_attempts_chunk_id_fkey'), 'practice_attempts', 'curriculum_chunks', ['chunk_id'], ['id'])
    op.alter_column('practice_attempts', 'chunk_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('practice_attempts', 'reference_answer')
    op.drop_column('practice_attempts', 'lesson_title')
    op.drop_column('practice_attempts', 'question_content')
    op.drop_column('practice_attempts', 'question_number')
    # ### end Alembic commands ###
