"""add attempt concept diagnosis

Revision ID: b5580545cd26
Revises: b2a6aabcbe64
Create Date: 2026-09-05 10:39:47.638560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5580545cd26'
down_revision: Union[str, Sequence[str], None] = 'b2a6aabcbe64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practice_attempt_concepts', sa.Column('diagnosis_status', sa.String(length=50), nullable=True))
    op.add_column('practice_attempt_concepts', sa.Column('diagnosis_reason', sa.Text(), nullable=True))
    op.add_column('practice_attempt_concepts', sa.Column('diagnosis_source', sa.String(length=50), nullable=True))
    op.add_column('practice_attempt_concepts', sa.Column('diagnosed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('practice_attempt_concepts', 'diagnosed_at')
    op.drop_column('practice_attempt_concepts', 'diagnosis_source')
    op.drop_column('practice_attempt_concepts', 'diagnosis_reason')
    op.drop_column('practice_attempt_concepts', 'diagnosis_status')
    # ### end Alembic commands ###
