"""add curriculum chunks table

Revision ID: c62e591b996a
Revises: a0a15111c842
Create Date: 2026-09-02 23:20:31.689647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c62e591b996a'
down_revision: Union[str, Sequence[str], None] = 'a0a15111c842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curriculum_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('chunk_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('question_number', sa.String(length=50), nullable=True),
    sa.Column('lesson_number', sa.String(length=50), nullable=True),
    sa.Column('lesson_title', sa.String(length=255), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['curriculum_pages.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['curriculum_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curriculum_chunks_page_id'), 'curriculum_chunks', ['page_id'], unique=False)
    op.create_index(op.f('ix_curriculum_chunks_section_id'), 'curriculum_chunks', ['section_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_curriculum_chunks_section_id'), table_name='curriculum_chunks')
    op.drop_index(op.f('ix_curriculum_chunks_page_id'), table_name='curriculum_chunks')
    op.drop_table('curriculum_chunks')
    # ### end Alembic commands ###
