"""add question group concept mappings

Revision ID: ff2688a033ef
Revises: 66deed8153a3
Create Date: 2026-09-06 00:21:11.366243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff2688a033ef'
down_revision: Union[str, Sequence[str], None] = '66deed8153a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curriculum_question_group_concepts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_group_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['curriculum_concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_group_id'], ['curriculum_question_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_group_id', 'concept_id', name='uq_curriculum_question_group_concept')
    )
    op.create_index(op.f('ix_curriculum_question_group_concepts_concept_id'), 'curriculum_question_group_concepts', ['concept_id'], unique=False)
    op.create_index(op.f('ix_curriculum_question_group_concepts_question_group_id'), 'curriculum_question_group_concepts', ['question_group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_curriculum_question_group_concepts_question_group_id'), table_name='curriculum_question_group_concepts')
    op.drop_index(op.f('ix_curriculum_question_group_concepts_concept_id'), table_name='curriculum_question_group_concepts')
    op.drop_table('curriculum_question_group_concepts')
    # ### end Alembic commands ###
